networks:
  default:

volumes:
  mysql_data:

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hackaton-backend-container
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "mysql://mysql:mysql@mysql:3306/hck2025"
    restart: unless-stopped
    networks:
      - default

  pyapi:
    build:
      context: ./pyapi
      dockerfile: Dockerfile
    container_name: hackaton-pyapi-container
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - default
    
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: hackaton-frontend-container
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - default

  mysql:
    image: mysql:8.1
    container_name: mysql_hck2025
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: hck2025
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql