networks:
  default:

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: hackaton-frontend:latest
    container_name: hackaton-frontend-container
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - default